[package]
name = "look_for_primes"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.1"
pixels = "0.15.0"
winit = { version = "0.30.12", features = ["rwh_05"] }
log = "0.4"
env_logger = "0.11.8"